TLSv1.2/1.3, listen on 443, fastcgi_pass to WordPress on port 9000. 

server {
    listen 443 ssl;
    ssl_protocols TLSv1.3
    root /var/www/html;
    location / {
        fastcgi_pass  wordpress:9000;
    }
}