services:
  mariadb_in:
    build: requirements/mariadb
    image: mariadb_in
    container_name: mariadb_in
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped # / always ?
  wordpress_in:
    build: requirements/wordpress
    image: wordpress_in
    container_name: wordpress_in
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      - mariadb_in
      - redis_in
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped 
  nginx_in:
    build: requirements/nginx
    image: nginx_in
    container_name: nginx_in
    depends_on:
      - wordpress_in
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    restart: unless-stopped 
  redis_in:
    build: requirements/bonus/redis
    image: redis_in
    container_name: redis_in
    networks:
      - inception
    restart: unless-stopped
  catsurf_in:
    build: requirements/bonus/webserv
    image: catsurf_in
    container_name: catsurf_in
    networks:
      - inception
    restart: unless-stopped
    ports:
      - "9090:9090"
      - "9110:9110"
  static_in:
    build: ./requirements/bonus/static
    image: static_in
    container_name: static_in
    networks:
     - inception
    restart: unless-stopped
  adminer_in:
    build: ./requirements/bonus/adminer
    image: adminer_in
    container_name: adminer_in
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: unless-stopped

networks:
  inception:

secrets:
  db_password:
    file: ../secrets/mysql_pw
  db_root_password:
    file: ../secrets/mysql_root_pw
  wp_admin_password:
    file: ../secrets/wp_admin_pw
  wp_user_password:
    file: ../secrets/wp_user_pw

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress