error_log /logs/error.log;
pid /logs/catsurf.pid;

server 
{
    listen 0.0.0.0:8080;
    server_name catsurf.com www.catsurf.com;
    root var/www;
    index index.html index.htm;
    error_page 404 /error_pages/404.html;
    client_max_body_size 22463463460;
    timeout 100;

    location /miao {
        index index.html;
    }

    location /stuff {
        root var/www/images;
        autoindex on;
    }

    location /idk {
        return 301 /miao;
    }

    location /err {
        return 404;
    }

    location /errorcss {
        root var/www/error_pages;
        index error.css;
    }
}

server 
{
    listen 9110;
    server_name default;
    root var/www/catshare;
    index index.html index.htm;
    error_page 404 /error_pages/404.html;
    client_max_body_size 4326236499999999999;
    timeout 100;

    location /catpics {
        allow_methods GET POST DELETE;
        root var/www/catshare/uploads;
        upload_path var/www/catshare/uploads;
        autoindex on;
        botdetect no;
    }
}
